version: '3.7'

services:
  api:
    build: ./api
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./api/:/app/
    ports:
      - 8000:8000
    environment:
      - SCRAPY_HOST=http://crawler:6800
      - SCRAPY_PROJECT=web-crawler

  crawler:
    build: ./crawler
    command: scrapyd
    volumes:
      - ./crawler/:/app/
    ports:
      - 6800:6800
