from scrapy.item import Item
from scrapy.item import Field


class Job(Item):
    rid = Field()
    uuid = Field()
    url = Field()
    location = Field()
    city = Field()
    state = Field()
    postal_code = Field()
    country = Field()
    street_address = Field()
    category_list = Field()
    summary = Field()
    description = Field()
    title = Field()
    apply_link = Field()
    job_type = Field()
    job_code = Field()
    job_status = Field()
    department = Field()
    salary_info = Field()
    email = Field()
    record_name = Field()
    is_internal = Field()
    users = Field()
    brand = Field()
    date_posted = Field()
    questionnaire_id = Field()
    custom_fields = Field()
    recruiter_name = Field()
    paradox_location = Field()
